{% set name = "xtb" %}
{% set pkg_name = "scine-" + name %}
{% set version = "1.0.2" %}

package:
  name: {{ pkg_name }}-pkg
  version: {{ version }}

source:
  - url: https://github.com/qcscine/xtb_wrapper/archive/refs/tags/{{ version }}.tar.gz
    sha256: 9beb1103467f3cfd9ad33beb2f3ec650bc3e6dc7094876774be3cc4e6f210487
    fn: {{ name }}.tar.gz
    patches:
      - patches/pkgconfig.patch
      - patches/clang.patch  # [osx]
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/5.0.1.tar.gz
    sha256: 089ca500fc191e04a968ea166d2fe80178b227bc2e6d3926523fa2eee5f6492d
    fn: dev.tar.gz
    folder: dev

build:
  number: 1
  skip: true  # [win]

outputs:
  - name: {{ pkg_name }}
    script: build_lib.sh
    build:
      run_exports:
        - {{ pin_subpackage(pkg_name, max_pin='x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - cmake
        - ninja
        - pkg-config
      host:
        - boost-cpp
        - eigen
        - libblas
        - scine-utilsos
        - xtb
      run:
        - boost-cpp

    test:
      commands:
        - test -f $PREFIX/lib/{{ name }}.module${SHLIB_EXT}

{% if linux and x86_64 %}
  - name: {{ pkg_name }}-python
    script: build_python.sh

    build:
      noarch: python

    requirements:
      host:
        - pip
        - python >=3.6
        - {{ pkg_name }} {{ version }}
      run:
        - python >=3.6
        - {{ pkg_name }} {{ version }}
        - scine-utilities-python

    test:
      imports:
        - scine_xtb_wrapper
      requires:
        - pip
      commands:
        - pip check
{% endif %}

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Wrapper around xtb to export it into the Scine tool chain.
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/xtb_wrapper

extra:
  recipe-maintainers:
    - awvwgk
  feedstock-name: {{ pkg_name }}
